site_name: Open
repo_name: tianheg/open
repo_url: https://github.com/tianheg/open
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.suggest
  include_search_page: true
  search_index_only: true

plugins:
  - search:
      lang:
        - ja

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

nav:
  - Classes:
    - index.md
    - 思维能力:
      - Learning How to Learn-Barbara Oakley: learning-how-to-learn.md
      - 批判性思维-谷振诣: critical-thinking.md
    - 人文修养:
      - 红楼梦-欧丽娟: dream-of-the-red-chamber.md
      - 影视鉴赏-张晓敏: film-appreciation.md
    - 科技博览:
      - 从爱因斯坦到霍金的宇宙-赵峥: einstein-to-hawking.md
      - 数学的思维方式与创新-丘维声: math-think-innovate.md
      - 积极心理学-Tal Ben-Shahar: positive-psychology-by-tal-ben-shahar.md
    - 专业技术:
      - CS Crash Course-Carrie Anne: cs-crash-course.md
  - Tools:
    - tools.md
    - Shell: shell.md
